# Generated by Django 5.2.17 on 2026-08-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('advertiser', '广告主'), ('monitor', '监察员')], default='advertiser', max_length=16, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
