# Generated by Django 5.2.17 on 2026-08-29 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=128, verbose_name='公司名称')),
                ('contact_name', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='详细地址')),
                ('license_url', models.URLField(blank=True, default='', max_length=512, verbose_name='营业执照')),
                ('area_id', models.IntegerField(default=0, verbose_name='地区ID')),
                ('area_path', models.CharField(blank=True, default='', max_length=255, verbose_name='地区名称')),
                ('audit_status', models.SmallIntegerField(choices=[(-1, '驳回'), (0, '审核中'), (1, '审核通过')], default=0, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '客户资料',
                'verbose_name_plural': '客户资料',
                'db_table': 'customer_profile',
            },
        ),
    ]
