# Generated by Django 5.2.17 on 2026-08-15 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='广告主名称')),
                ('contact_mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('paused', '暂停')], default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '广告主',
                'verbose_name_plural': '广告主',
                'db_table': 'ads_advertiser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('kuaishou', '快手'), ('toutiao', '头条'), ('wechat', '微信'), ('bilibili', 'B站'), ('other', '其他')], default='other', max_length=16, verbose_name='投放平台')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预算')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '投放中'), ('paused', '已暂停'), ('ended', '已结束')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ads.advertiser', verbose_name='广告主')),
            ],
            options={
                'verbose_name': '广告活动',
                'verbose_name_plural': '广告活动',
                'db_table': 'ads_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='素材名称')),
                ('material_type', models.CharField(choices=[('video', '视频'), ('image', '图片'), ('text', '图文')], max_length=16, verbose_name='素材类型')),
                ('file_url', models.URLField(blank=True, verbose_name='素材地址')),
                ('duration', models.IntegerField(blank=True, help_text='视频时长秒', null=True, verbose_name='视频时长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.campaign', verbose_name='广告活动')),
            ],
            options={
                'verbose_name': '广告素材',
                'verbose_name_plural': '广告素材',
                'db_table': 'ads_creative',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('keyword', '关键词'), ('budget_overrun', '预算超支'), ('platform_violation', '平台违规'), ('custom', '自定义')], max_length=32, verbose_name='规则类型')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_rules', to='ads.advertiser', verbose_name='广告主')),
            ],
            options={
                'verbose_name': '监控规则',
                'verbose_name_plural': '监控规则',
                'db_table': 'ads_monitor_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='违规描述')),
                ('screenshot_url', models.URLField(blank=True, verbose_name='截图地址')),
                ('detected_at', models.DateTimeField(verbose_name='检测时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_records', to='ads.campaign', verbose_name='广告活动')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_records', to='ads.monitorrule', verbose_name='监控规则')),
            ],
            options={
                'verbose_name': '违规记录',
                'verbose_name_plural': '违规记录',
                'db_table': 'ads_violation_record',
                'ordering': ['-detected_at'],
            },
        ),
    ]
