# Generated by Django 5.2.17 on 2026-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvPlatform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='平台位ID')),
                ('epg_name', models.CharField(max_length=200, verbose_name='广告名称')),
                ('element_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('element_type', models.IntegerField(choices=[(0, '图片'), (1, '视频')], default=1, verbose_name='素材类型')),
                ('element_url', models.URLField(blank=True, verbose_name='素材地址')),
                ('hot_img_url', models.URLField(blank=True, verbose_name='封面图地址')),
                ('dulation', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('byte_rate', models.IntegerField(default=0, verbose_name='码率')),
                ('frame_rate', models.IntegerField(default=0, verbose_name='帧率')),
                ('definition', models.CharField(blank=True, max_length=32, verbose_name='分辨率')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('ext', models.CharField(blank=True, max_length=16, verbose_name='扩展名')),
                ('md_5', models.CharField(blank=True, max_length=64, verbose_name='文件MD5')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('cname', models.CharField(blank=True, max_length=64, verbose_name='上传人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '广告平台位',
                'verbose_name_plural': '广告平台位',
                'db_table': 'ads_adv_platform',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='楼宇ID')),
                ('name', models.CharField(max_length=200, verbose_name='楼宇名称')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否已选投放')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
            ],
            options={
                'verbose_name': '楼宇',
                'verbose_name_plural': '楼宇',
                'db_table': 'ads_building',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='status',
            field=models.CharField(choices=[('pending', '审核中'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审核状态'),
        ),
    ]
