# Generated by Django 5.2.17 on 2026-08-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_seed_mock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='cover_url',
            field=models.CharField(blank=True, default='', help_text='视频封面图（本地相对路径，无则为空）', max_length=500, verbose_name='封面地址'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.campaign', verbose_name='广告活动'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='file_url',
            field=models.CharField(blank=True, help_text='本地相对路径 /media/... 或完整 URL', max_length=500, verbose_name='素材地址'),
        ),
    ]
